/**
 * @file types/index.ts
 * @description All TypeScript types for the TraceLens CLI.
 */

// ─── Config File ───────────────────────────────────────────────────────────────

/**
 * Schema for .tracelensrc.json — the local configuration file.
 * Generated by `tracelens init`, consumed by `tracelens audit`.
 */
export interface TraceLensConfig {
  /** Routes/pages to audit */
  routes: string[];
  /** Device mode */
  device: "desktop" | "mobile";
  /** Network throttle */
  throttle: "none" | "4g" | "3g";
  /** Number of Lighthouse runs for averaging */
  runs: number;
  /** Enable AI root-cause analysis */
  ai: boolean;
  /** Report output directory */
  outputDir: string;
  /** Optional bundle analysis config */
  bundle?: {
    webpackStatsPath?: string;
    framework?: string;
  };
}

// ─── CLI Options ───────────────────────────────────────────────────────────────

/** Options accepted by `tracelens audit` */
export interface AuditOptions {
  device: "desktop" | "mobile";
  runs: string; // string from commander, parsed to int in command
  ai: boolean;
  output: string;
  open: boolean;
  verbose: boolean;
  throttle: "none" | "4g" | "3g";
  bundle?: string;
  json: boolean;        // Machine-readable JSON output
  ci: boolean;          // CI mode: no spinners, compact logs, strict exit codes
  saveSession: boolean; // Persist full session metadata
}

/** Options accepted by `tracelens compare` */
export interface CompareOptions {
  open: boolean;
  output: string;
  json: boolean;           // Machine-readable JSON output
  failOnRegression: boolean; // Exit 1 on any regression
}

/** Options accepted by `tracelens init` */
export interface InitOptions {
  force: boolean;
}

/** Options accepted by `tracelens doctor` */
export interface DoctorOptions {
  json: boolean;
}

/** Options accepted by `tracelens analyze` */
export interface AnalyzeOptions {
  output: string;
  json: boolean;
  open: boolean;
  verbose: boolean;
  provider?: string; // Override AI provider
}

// ─── Audit Result (compact CLI view) ──────────────────────────────────────────

/** Flattened vitals summary for CLI display */
export interface VitalsSummary {
  lcp: number | null;
  fcp: number | null;
  tbt: number | null;
  cls: number | null;
  ttfb: number | null;
  score: number | null;
}

/** Summary of one audited route */
export interface RouteSummary {
  url: string;
  label: string;
  vitals: VitalsSummary;
  primaryBottleneck: string | null;
  risksCount: number;
  artifactPaths: {
    json: string | null;
    html: string | null;
    screenshot: string | null;
  };
}

/** Top-level audit session summary */
export interface AuditSummary {
  sessionId: string;
  url: string;
  device: string;
  durationMs: number;
  success: boolean;
  routes: RouteSummary[];
  outputDir: string;
}

// ─── Comparison ────────────────────────────────────────────────────────────────

export type Trend = "improved" | "regressed" | "unchanged";

export interface VitalComparison {
  metric: string;
  before: number | null;
  after: number | null;
  diffMs: number | null;
  diffPct: number | null;
  trend: Trend;
  threshold: "good" | "needs-improvement" | "poor";
}

export interface ComparisonResult {
  url: string;
  before: { sessionId: string; reportPath: string };
  after: { sessionId: string; reportPath: string };
  vitals: VitalComparison[];
  regressions: string[];
  improvements: string[];
  summary: string;
}

// ─── Doctor ───────────────────────────────────────────────────────────────────

export type CheckStatus = "pass" | "fail" | "warn" | "skip";

export interface DiagnosticCheck {
  name: string;
  status: CheckStatus;
  message: string;
  fix?: string;
}

export interface DoctorReport {
  passed: number;
  failed: number;
  warnings: number;
  checks: DiagnosticCheck[];
  readyToAudit: boolean;
}

// ─── Session Metadata ─────────────────────────────────────────────────────────

/** Full session metadata saved when --save-session is used */
export interface SessionMetadata {
  sessionId: string;
  generatedAt: string;
  cliVersion: string;
  command: string;
  url: string;
  config: Record<string, unknown>;
  stages: Record<string, { status: string; durationMs: number | null }>;
  ai: {
    provider: unknown;
    model: unknown;
    durationMs: unknown;
    tokens: unknown;
    status: string;
  } | null;
  artifacts: string[];
  totalDurationMs: number;
}

// ─── JSON Output Envelope ─────────────────────────────────────────────────────

/** Envelope emitted to stdout when --json flag is active */
export interface JsonOutputEnvelope<T = unknown> {
  tracelens: string;  // version
  command: string;
  timestamp: string;
  success: boolean;
  data: T;
  errors?: string[];
}
