/**
 * @file types.ts
 * @description Type contract for @tracelens/ai-engine.
 *
 * Defines:
 *   - Provider abstraction interface
 *   - AI analysis output (AIRootCauseReport)
 *   - Engine configuration
 *   - Observability metadata
 */

// ─── Provider Abstraction ──────────────────────────────────────────────────────

export type AIProviderName = "openai" | "gemini" | "anthropic" | "openrouter";

export interface AIProviderConfig {
  /** Which AI provider to use */
  provider: AIProviderName;
  /** Model identifier (e.g. "gemini-2.5-flash", "gpt-4o-mini") */
  model: string;
  /** API key for the provider (loaded from env, never hardcoded) */
  apiKey: string;
  /** Temperature (default 0.1 for deterministic output) */
  temperature: number;
  /** Max tokens for response */
  maxTokens: number;
}

export interface AICompletion {
  /** Raw text response from the AI */
  text: string;
  /** Token usage (if reported by provider) */
  usage: {
    promptTokens: number | null;
    completionTokens: number | null;
    totalTokens: number | null;
  };
  /** Provider-reported model used */
  model: string;
}

/** Abstract provider interface — all providers must implement this */
export interface AIProvider {
  readonly name: AIProviderName;
  readonly model: string;
  complete(systemPrompt: string, userPrompt: string): Promise<AICompletion>;
}

// ─── AI Root-Cause Report ──────────────────────────────────────────────────────

export interface AIRootCause {
  /** Priority rank (1 = highest impact) */
  rank: number;
  /** Short issue label */
  issue: string;
  /** Detailed explanation referencing actual metrics */
  explanation: string;
  /** Key metrics cited as evidence */
  metrics: Record<string, string | number>;
  /** Severity: critical | high | medium | low */
  severity: "critical" | "high" | "medium" | "low";
  /** Estimated impact on user experience */
  impact: string;
}

export interface AIRecommendation {
  /** Priority rank (1 = most impactful) */
  rank: number;
  /** Specific action to take */
  action: string;
  /** WHY this will help — tied to the actual data */
  rationale: string;
  /** Expected performance gain (e.g., "~700ms LCP improvement") */
  estimatedImpact: string;
  /** Implementation effort */
  effort: "low" | "medium" | "high";
  /** Priority classification */
  priority: "critical" | "high" | "medium" | "low";
  /** Category */
  category: "bundle" | "javascript" | "network" | "server" | "images" | "rendering";
}

export interface AIEstimatedImpact {
  /** Estimated LCP improvement (e.g., "~700ms") */
  lcp: string | null;
  /** Estimated FCP improvement */
  fcp: string | null;
  /** Estimated TBT reduction */
  tbt: string | null;
  /** Overall performance score change */
  performanceScore: string | null;
  /** General note */
  note: string;
}

export interface AIConfidenceReport {
  /** Overall confidence 0–1 */
  overall: number;
  /** Data quality: high | medium | low */
  dataQuality: "high" | "medium" | "low";
  /** What sources were available */
  sourcesUsed: string[];
  /** Caveats or limitations */
  note: string | null;
}

/**
 * The canonical AI Root-Cause Analysis Report.
 * Generated by the AI engine, consumed by the dashboard, CLI, and CI/CD.
 */
export interface AIRootCauseReport {
  /** 2–3 sentence executive summary of performance health */
  summary: string;
  /** The AI-identified primary bottleneck */
  primaryBottleneck: {
    type: string;
    explanation: string;
    evidence: string[];
  };
  /** Ordered list of root causes (max 5) */
  rootCauses: AIRootCause[];
  /** Ordered list of recommendations (max 7) */
  recommendations: AIRecommendation[];
  /** Estimated performance impact of implementing all recommendations */
  estimatedImpact: AIEstimatedImpact;
  /** Confidence in the analysis */
  confidence: AIConfidenceReport;
}

// ─── Engine Output ─────────────────────────────────────────────────────────────

export type AIEngineStatus = "success" | "skipped" | "failed";

export interface AIEngineObservability {
  /** Which provider was used */
  provider: AIProviderName | null;
  /** Which model was used */
  model: string | null;
  /** Token usage */
  usage: AICompletion["usage"] | null;
  /** Time to complete AI call (ms) */
  durationMs: number;
  /** Prompt character count (for token estimation) */
  promptCharCount: number;
}

/** Final output of the AI engine */
export interface AIEngineResult {
  /** Whether AI analysis ran successfully */
  status: AIEngineStatus;
  /** Human-readable status message */
  message: string;
  /** The root-cause analysis (null if skipped/failed) */
  report: AIRootCauseReport | null;
  /** Observability metadata */
  meta: AIEngineObservability;
}

// ─── Engine Config ─────────────────────────────────────────────────────────────

export interface AIEngineConfig {
  /** Provider config (auto-loaded from env if not provided) */
  provider?: Partial<AIProviderConfig>;
  /** Whether to log prompts to console (default: false) */
  logPrompts?: boolean;
  /** Whether to write full prompt+response to disk (default: false) */
  saveDebugLogs?: boolean;
  /** Output directory for debug logs */
  debugLogDir?: string;
}
